### PR TITLE
Updated Twee 2 install instructions

### PR DESCRIPTION
**Pull request by catdad666**
Added a line that opens the Twee 2 folder

### CODE REVIEW

**Comment by whymog** [comment]
Looks good to me!

**Review by whymog — APPROVED** [review]

**Review by thenthdegree — APPROVED** [review]
My review is that this change is very good, no problems

**Comment by thenthdegree** [comment]
This is the comment box, and I'm typing in it

**Comment by thenthdegree** [comment]
eff that dumb branch

**Pull request merged**
